app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'

urlpatterns=[
    path('vijji/',vijji,name='vijji'),
    path('akhi/',akhi,name='akhi'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='app2'

urlpatterns=[
    path('sai/',sai,name='sai'),
    path('chinni/',chinni,name='chinni'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def vijji(request):
    return render(request,'vijji.html')

def akhi(request):
    return render(request,'akhi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def sai(request):
    return render(request,'sai.html')

def chinni(request):
    return render(request,'chinni.html')

templates/akhi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>akhi</title>
</head>
<body>
    <center>
        <h1>this is akhi page</h1>
        <h1>this is app1 page</h1>
        <a href="{% url 'app2:sai' %}">navigate to sai page</a><br>
        <a href="{% url 'app2:chinni' %}">navigate to chinni page</a><br>
        <a href="{% url 'app1:vijji' %}">navigate to vijji page</a><br>
    </center>
</body>
</html>

templates/chinni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>chinni</title>
</head>
<body>
    <center>
        <h1>this is chinni page</h1>
        <h1>this is app2 page</h1>
        <a href="{% url 'app2:sai' %}">navigate to sai page</a><br>
        <a href="{% url 'app1:vijji' %}">navigate to chinni page</a><br>
        <a href="{% url 'app1:akhi' %}">navigate to akhi page</a><br>
    </center>
</body>
</html>

templates/sai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sai</title>
</head>
<body>
    <center>
        <h1>this is sai page</h1>
        <h1>this is app2 page</h1>
        <a href="{% url 'app2:chinni' %}">navigate to sai page</a><br>
        <a href="{% url 'app1:vijji' %}">navigate to chinni page</a><br>
        <a href="{% url 'app1:akhi' %}">navigate to akhi page</a><br>
    </center>
</body>
</html>

templates/vijji.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>vijji</title>
</head>
<body>
    <center>
        <h1>this is vijji page</h1>
        <h1>this is app1 page</h1>
        <a href="{% url 'app2:sai' %}">navigate to sai page</a><br>
        <a href="{% url 'app2:chinni' %}">navigate to chinni page</a><br>
        <a href="{% url 'app1:akhi' %}">navigate to akhi page</a><br>
    </center>
</body>
</html>